// Baza locala de retete romanesti - functioneaza si fara internet
const LOCAL_RECIPES = [
{
id:"local-1",
emoji:"🍗",
title_ro:"Tocăniță de pui cu cartofi",
title_en:"Chicken stew with potatoes",
category_ro:"Fel principal", category_en:"Main dish",
time:45, servings:4, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["500g pulpe de pui","4 cartofi","1 ceapă","2 căței usturoi","2 roșii","2 linguri ulei","sare","piper","pătrunjel"],
ingredients_en:["500g chicken legs","4 potatoes","1 onion","2 garlic cloves","2 tomatoes","2 tbsp oil","salt","pepper","parsley"],
steps_ro:["Taie ceapa mărunt și călește-o în ulei 3 minute.","Adaugă puiul și rumenește-l 8 minute.","Adaugă cartofii tăiați cuburi, roșiile, usturoiul, sare, piper și 500ml apă.","Fierbe 30 min la foc mic. Presară pătrunjel și servește."],
steps_en:["Chop onion and sauté in oil 3 min.","Add chicken and brown 8 min.","Add diced potatoes, tomatoes, garlic, salt, pepper and 500ml water.","Simmer 30 min. Sprinkle parsley and serve."],
tags:["pui","cartofi","ceapa","usturoi","rosii","chicken","potato","onion","garlic","tomato"]
},
{
id:"local-2",
emoji:"🍳",
title_ro:"Omletă cu brânză și roșii",
title_en:"Omelette with cheese and tomatoes",
category_ro:"Mic dejun", category_en:"Breakfast",
time:15, servings:2, difficulty_ro:"Foarte ușor", difficulty_en:"Very easy",
ingredients_ro:["4 ouă","1 roșie","50g brânză","1 ceapă verde","sare","piper","1 lingură unt"],
ingredients_en:["4 eggs","1 tomato","50g cheese","1 spring onion","salt","pepper","1 tbsp butter"],
steps_ro:["Bate ouăle cu sare și piper.","Taie roșia și ceapa.","Topește untul, adaugă legumele 2 min.","Toarnă ouăle, presară brânza, gătește 5 min cu capac."],
steps_en:["Beat eggs with salt and pepper.","Dice tomato and onion.","Melt butter, cook veggies 2 min.","Pour eggs, add cheese, cook 5 min covered."],
tags:["oua","rosii","branza","ceapa","eggs","tomato","cheese","onion"]
},
{
id:"local-3",
emoji:"🍝",
title_ro:"Paste aglio e olio (cu usturoi și ulei)",
title_en:"Pasta aglio e olio",
category_ro:"Fel principal", category_en:"Main dish",
time:20, servings:2, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["200g spaghetti","4 căței usturoi","50ml ulei de măsline","fulgi de chilli","pătrunjel","parmezan","sare"],
ingredients_en:["200g spaghetti","4 garlic cloves","50ml olive oil","chilli flakes","parsley","parmesan","salt"],
steps_ro:["Fierbe pastele în apă cu sare.","Feliază usturoiul și prăjește-l ușor în ulei (nu-l arde).","Adaugă chilli + un polonic de apă de la paste.","Amestecă pastele 2 min, adaugă pătrunjel și parmezan."],
steps_en:["Boil pasta in salted water.","Slice garlic and gently fry in oil.","Add chilli + a ladle of pasta water.","Toss pasta 2 min, add parsley and parmesan."],
tags:["paste","usturoi","ulei","parmezan","pasta","garlic","oil","spaghetti"]
},
{
id:"local-4",
emoji:"🍅",
title_ro:"Supă de roșii cu orez",
title_en:"Tomato soup with rice",
category_ro:"Supă", category_en:"Soup",
time:30, servings:4, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["800g roșii","1 ceapă","1 morcov","50g orez","1 lingură ulei","sare","busuioc"],
ingredients_en:["800g tomatoes","1 onion","1 carrot","50g rice","1 tbsp oil","salt","basil"],
steps_ro:["Călește ceapa și morcovul.","Adaugă roșiile și 1L apă, fierbe 15 min.","Adaugă orezul, mai fierbe 15 min.","Blendează (opțional), adaugă busuioc."],
steps_en:["Sauté onion and carrot.","Add tomatoes and 1L water, boil 15 min.","Add rice, boil 15 more min.","Blend (optional), add basil."],
tags:["rosii","orez","ceapa","morcov","tomato","rice","onion","carrot","supa","soup"]
},
{
id:"local-5",
emoji:"🥗",
title_ro:"Salată de ton cu porumb",
title_en:"Tuna salad with corn",
category_ro:"Salată", category_en:"Salad",
time:10, servings:2, difficulty_ro:"Foarte ușor", difficulty_en:"Very easy",
ingredients_ro:["1 conservă ton","1 conservă porumb","1 ceapă roșie","1 roșie","măsline","lămâie","ulei de măsline","sare"],
ingredients_en:["1 tuna can","1 corn can","1 red onion","1 tomato","olives","lemon","olive oil","salt"],
steps_ro:["Scurge tonul și porumbul.","Taie roșia și ceapa.","Amestecă tot cu măsline, lămâie și ulei."],
steps_en:["Drain tuna and corn.","Chop tomato and onion.","Mix all with olives, lemon and oil."],
tags:["ton","porumb","ceapa","rosii","tuna","corn","onion","tomato","salata"]
},
{
id:"local-6",
emoji:"🥔",
title_ro:"Cartofi la cuptor cu usturoi",
title_en:"Roasted potatoes with garlic",
category_ro:"Garnitură", category_en:"Side dish",
time:50, servings:4, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["1kg cartofi","5 căței usturoi","3 linguri ulei","rozmarin","sare","piper","boia"],
ingredients_en:["1kg potatoes","5 garlic cloves","3 tbsp oil","rosemary","salt","pepper","paprika"],
steps_ro:["Taie cartofii în sferturi lungi.","Amestecă cu ulei, usturoi, condimente.","Coace 40 min la 200°C, întoarce-i la jumătate."],
steps_en:["Cut potatoes in wedges.","Toss with oil, garlic, spices.","Bake 40 min at 200°C, flip halfway."],
tags:["cartofi","usturoi","potato","garlic"]
},
{
id:"local-7",
emoji:"🍚",
title_ro:"Orez cu legume",
title_en:"Vegetable fried rice",
category_ro:"Fel principal", category_en:"Main dish",
time:25, servings:3, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["250g orez","1 morcov","1 ardei","100g mazăre","2 ouă","sos de soia","ceapă verde","ulei"],
ingredients_en:["250g rice","1 carrot","1 bell pepper","100g peas","2 eggs","soy sauce","spring onion","oil"],
steps_ro:["Fierbe orezul.","Călește legumele 5 min.","Adaugă ouăle bătute, amestecă.","Adaugă orezul + sos de soia, prăjește 5 min."],
steps_en:["Cook rice.","Stir-fry veggies 5 min.","Add beaten eggs, scramble.","Add rice + soy sauce, fry 5 min."],
tags:["orez","morcov","ardei","mazare","oua","rice","carrot","pepper","peas","eggs"]
},
{
id:"local-8",
emoji:"🥞",
title_ro:"Clătite simple",
title_en:"Simple pancakes / crepes",
category_ro:"Desert", category_en:"Dessert",
time:30, servings:6, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["300g făină","3 ouă","500ml lapte","100ml apă minerală","2 linguri zahăr","1 praf sare","ulei","gem sau ciocolată"],
ingredients_en:["300g flour","3 eggs","500ml milk","100ml sparkling water","2 tbsp sugar","pinch salt","oil","jam or chocolate"],
steps_ro:["Amestecă făina, ouăle, laptele, apa, zahărul, sarea.","Lasă aluatul 10 min.","Coace clătitele 2 min pe fiecare parte.","Umple cu gem/ciocolată."],
steps_en:["Mix flour, eggs, milk, water, sugar, salt.","Rest 10 min.","Cook 2 min per side.","Fill with jam/chocolate."],
tags:["faina","oua","lapte","zahar","flour","eggs","milk","sugar","desert"]
},
{
id:"local-9",
emoji:"🫘",
title_ro:"Fasole bătută cu ceapă caramelizată",
title_en:"Mashed beans with caramelized onion",
category_ro:"Aperitiv", category_en:"Appetizer",
time:40, servings:4, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["400g fasole albă","2 cepe","3 căței usturoi","ulei","sare","boia","pătrunjel"],
ingredients_en:["400g white beans","2 onions","3 garlic cloves","oil","salt","paprika","parsley"],
steps_ro:["Fierbe fasolea (sau folosește conservă).","Blendează cu usturoi, ulei, sare.","Caramelizează ceapa cu boia.","Servește cu ceapă deasupra."],
steps_en:["Boil beans (or use canned).","Blend with garlic, oil, salt.","Caramelize onion with paprika.","Top with onion."],
tags:["fasole","ceapa","usturoi","beans","onion","garlic"]
},
{
id:"local-10",
emoji:"🍲",
title_ro:"Ciorbă de legume",
title_en:"Vegetable soup",
category_ro:"Supă", category_en:"Soup",
time:35, servings:5, difficulty_ro:"Ușor", difficulty_en:"Easy",
ingredients_ro:["2 cartofi","1 morcov","1 ceapă","1 ardei","1 dovlecel","2 roșii","leuștean","sare","borș (opțional)"],
ingredients_en:["2 potatoes","1 carrot","1 onion","1 bell pepper","1 zucchini","2 tomatoes","lovage","salt","borsch (optional)"],
steps_ro:["Taie legumele cuburi.","Fierbe 25 min în 2L apă cu sare.","Adaugă roșiile + borș, mai fierbe 10 min.","Adaugă leuștean."],
steps_en:["Dice veggies.","Boil 25 min in 2L salted water.","Add tomatoes + borsch, boil 10 min.","Add lovage."],
tags:["cartofi","morcov","ceapa","ardei","dovlecel","rosii","potato","carrot","onion","pepper","zucchini","tomato"]
},
{
id:"local-11",
emoji:"🍄",
title_ro:"Pui cu smântână și ciuperci",
title_en:"Chicken with sour cream and mushrooms",
category_ro:"Fel principal", category_en:"Main dish",
time:35, servings:4, difficulty_ro:"Mediu", difficulty_en:"Medium",
ingredients_ro:["500g piept de pui","300g ciuperci","1 ceapă","200ml smântână","2 căței usturoi","ulei","sare","piper","mărar"],
ingredients_en:["500g chicken breast","300g mushrooms","1 onion","200ml sour cream","2 garlic cloves","oil","salt","pepper","dill"],
steps_ro:["Taie puiul fâșii, rumenește-l.","Adaugă ceapa, ciupercile, usturoiul, gătește 10 min.","Adaugă smântâna, fierbe 5 min.","Presară mărar, servește cu orez/piure."],
steps_en:["Slice chicken, brown it.","Add onion, mushrooms, garlic, cook 10 min.","Add sour cream, simmer 5 min.","Sprinkle dill, serve with rice/mash."],
tags:["pui","ciuperci","smantana","ceapa","usturoi","chicken","mushrooms","cream","onion","garlic"]
},
{
id:"local-12",
emoji:"🍞",
title_ro:"Bruschete cu roșii și mozzarella",
title_en:"Bruschetta with tomatoes and mozzarella",
category_ro:"Aperitiv", category_en:"Appetizer",
time:15, servings:4, difficulty_ro:"Foarte ușor", difficulty_en:"Very easy",
ingredients_ro:["1 baghetă","3 roșii","1 mozzarella","2 căței usturoi","busuioc","ulei de măsline","sare"],
ingredients_en:["1 baguette","3 tomatoes","1 mozzarella","2 garlic cloves","basil","olive oil","salt"],
steps_ro:["Prăjește feliile de baghetă.","Freacă cu usturoi.","Adaugă roșii + mozzarella + busuioc + ulei."],
steps_en:["Toast baguette slices.","Rub with garlic.","Top with tomatoes + mozzarella + basil + oil."],
tags:["paine","rosii","mozzarella","usturoi","bread","tomato","garlic","branza"]
}
];
